<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brady Miller">

<title>Weekly Summary Template</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="index_files/libs/htmlwidgets-1.6.1/htmlwidgets.js"></script>
<script src="index_files/libs/plotly-binding-4.10.1/plotly.js"></script>
<script src="index_files/libs/typedarray-0.1/typedarray.min.js"></script>
<script src="index_files/libs/jquery-3.5.1/jquery.min.js"></script>
<link href="index_files/libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="index_files/libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="index_files/libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="index_files/libs/plotly-main-2.11.1/plotly-latest.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Weekly Summary Template</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Brady Miller </p>
            </div>
    </div>
      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#tuesday-february-7th" id="toc-tuesday-february-7th" class="nav-link active" data-scroll-target="#tuesday-february-7th">Tuesday, February 7th</a></li>
  <li><a href="#tuesday-february-9th" id="toc-tuesday-february-9th" class="nav-link" data-scroll-target="#tuesday-february-9th">Tuesday, February 9th</a></li>
  </ul>
</nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.4.0     ✔ purrr   1.0.1
✔ tibble  3.1.8     ✔ dplyr   1.1.0
✔ tidyr   1.3.0     ✔ stringr 1.5.0
✔ readr   2.1.3     ✔ forcats 1.0.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'

The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
</div>
<section id="tuesday-february-7th" class="level2">
<h2 class="anchored" data-anchor-id="tuesday-february-7th">Tuesday, February 7th</h2>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
TIL
</div>
</div>
<div class="callout-body-container callout-body">
<p>Include a <em>very brief</em> summary of what you learnt in this class here.</p>
<p>Today, I learnt the following concepts in class:</p>
<ol type="1">
<li>What the interpretation of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> is (regression coefficients)</li>
<li>Categorical covariates</li>
<li>How to reorder factors</li>
</ol>
</div>
</div>
<section id="interpretation-of-_0-and-beta_1-regression-coefficients" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-_0-and-beta_1-regression-coefficients">Interpretation of $_0&nbsp;and <span class="math inline">\(\beta_1\)</span> (regression coefficients)</h4>
<ul>
<li>The regression model is…</li>
</ul>
<p><span class="math inline">\(y_i = \beta_0 + \beta_1 x_i + \epsilon_i\)</span></p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the regression coefficients with <span class="math inline">\(\beta_0\)</span> being the intercept and <span class="math inline">\(\beta_1\)</span> being the slope</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(mtcars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from package:ggplot2:

    mpg</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> mtcars<span class="sc">$</span>hp</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> mtcars<span class="sc">$</span>mpg</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.7121 -2.1122 -0.8854  1.5819  8.2360 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 30.09886    1.63392  18.421  &lt; 2e-16 ***
x           -0.06823    0.01012  -6.742 1.79e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.863 on 30 degrees of freedom
Multiple R-squared:  0.6024,    Adjusted R-squared:  0.5892 
F-statistic: 45.46 on 1 and 30 DF,  p-value: 1.788e-07</code></pre>
</div>
</div>
<p>Based on the summary model…</p>
<ul>
<li><p>The intercept means that a car with ‘hp=0’ would have ‘mpg=30.09’ ## Thursday, February 9th</p></li>
<li><p>From this, if we have some co-variate <span class="math inline">\(x_0\)</span>, then the expected value for <span class="math inline">\(y(x_0)\)</span> is given by:</p></li>
</ul>
<p><span class="math display">\[y(x_0) = \beta_0 + \beta_1 x_0\]</span></p>
<ul>
<li>Using this we can find the expected value for <span class="math inline">\(x_0 + 1\)</span>, which is…</li>
</ul>
<p>$$ <span class="math display">\[\begin{align}
y(x_0 + 1) = \beta_0 + \beta_1 \times (x_0 + 1)\\ \\
&amp;= \beta_0 + \beta_1 x_0 + \beta_1\\ \\
&amp;= y(x_0) + \beta_1\\ \\above

\implies \beta_1 &amp;= y(x_0 + 1) - y(x_0)
\end{align}\]</span> $$</p>
</section>
<section id="categorical-covariates" class="level4">
<h4 class="anchored" data-anchor-id="categorical-covariates">Categorical covariates</h4>
<p>In class, we looked at categorical covariates in the iris dataset, and created a boxplot and a summary of the model for the categorical covariates</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> iris<span class="sc">$</span>Species</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> iris<span class="sc">$</span>Sepal.Length</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># boxplot(Sepal.Length ~ Species, df)</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(y <span class="sc">~</span> x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cat_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Species, iris)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>cat_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Length ~ Species, data = iris)

Coefficients:
      (Intercept)  Speciesversicolor   Speciesvirginica  
            5.006              0.930              1.582  </code></pre>
</div>
</div>
<p>Even if <span class="math inline">\(x\)</span> is categorical, we can still write down the regression model as follows: <span class="math display">\[
y_i = \beta_0 + \beta_1 x_i
\]</span> where <span class="math inline">\(x_i \in \{setosa, \ versicolor, \ virginica \}\)</span>. This means that we end up with, three different models with each one having a different intercept.</p>
<ol type="1">
<li><span class="math inline">\(y_i = \beta_0 + \beta_1 (x_i == 'setosa')\)</span></li>
<li><span class="math inline">\(y_i = \beta_0 + \beta_1 (x_i == 'versicolor')\)</span></li>
<li><span class="math inline">\(y_i = \beta_0 + \beta_1 (x_i == 'virginica')\)</span></li>
</ol>
<ul>
<li><p>The interpretation of the intercept (<span class="math inline">\(\beta_0\)</span>) is the expected y value when x belongs to the base category</p></li>
<li><p>The slope (<span class="math inline">\(\beta_1\)</span>) with the name ‘Species.versicolor’ represents the following:</p></li>
<li><p>‘(Intercept)’ = <span class="math inline">\(y(x = \texttt{setosa})\)</span></p></li>
<li><p>‘Species.versicolor’ = <span class="math inline">\(y(x = \texttt{versicolor}) - y(x = \texttt{setosa})\)</span></p></li>
<li><p>‘Species.virginica’ = <span class="math inline">\(y(x = \texttt{virginica}) - y(x = \texttt{setosa})\)</span></p></li>
</ul>
</section>
<section id="reordering-factors" class="level4">
<h4 class="anchored" data-anchor-id="reordering-factors">Reordering factors</h4>
<p>Lets say that we didn’t want ‘setosa’ to be the baseline level, and instead, we wanted ‘virginica’ to be the baseline level. How would we do this?</p>
<p>First we reorder/relevel the categorical covariate</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># before</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">$</span>Species</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] setosa     setosa     setosa     setosa     setosa     setosa    
  [7] setosa     setosa     setosa     setosa     setosa     setosa    
 [13] setosa     setosa     setosa     setosa     setosa     setosa    
 [19] setosa     setosa     setosa     setosa     setosa     setosa    
 [25] setosa     setosa     setosa     setosa     setosa     setosa    
 [31] setosa     setosa     setosa     setosa     setosa     setosa    
 [37] setosa     setosa     setosa     setosa     setosa     setosa    
 [43] setosa     setosa     setosa     setosa     setosa     setosa    
 [49] setosa     setosa     versicolor versicolor versicolor versicolor
 [55] versicolor versicolor versicolor versicolor versicolor versicolor
 [61] versicolor versicolor versicolor versicolor versicolor versicolor
 [67] versicolor versicolor versicolor versicolor versicolor versicolor
 [73] versicolor versicolor versicolor versicolor versicolor versicolor
 [79] versicolor versicolor versicolor versicolor versicolor versicolor
 [85] versicolor versicolor versicolor versicolor versicolor versicolor
 [91] versicolor versicolor versicolor versicolor versicolor versicolor
 [97] versicolor versicolor versicolor versicolor virginica  virginica 
[103] virginica  virginica  virginica  virginica  virginica  virginica 
[109] virginica  virginica  virginica  virginica  virginica  virginica 
[115] virginica  virginica  virginica  virginica  virginica  virginica 
[121] virginica  virginica  virginica  virginica  virginica  virginica 
[127] virginica  virginica  virginica  virginica  virginica  virginica 
[133] virginica  virginica  virginica  virginica  virginica  virginica 
[139] virginica  virginica  virginica  virginica  virginica  virginica 
[145] virginica  virginica  virginica  virginica  virginica  virginica 
Levels: setosa versicolor virginica</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">$</span>Species <span class="ot">&lt;-</span> <span class="fu">relevel</span>(iris<span class="sc">$</span>Species, <span class="st">"virginica"</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># after</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>iris<span class="sc">$</span>Species</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] setosa     setosa     setosa     setosa     setosa     setosa    
  [7] setosa     setosa     setosa     setosa     setosa     setosa    
 [13] setosa     setosa     setosa     setosa     setosa     setosa    
 [19] setosa     setosa     setosa     setosa     setosa     setosa    
 [25] setosa     setosa     setosa     setosa     setosa     setosa    
 [31] setosa     setosa     setosa     setosa     setosa     setosa    
 [37] setosa     setosa     setosa     setosa     setosa     setosa    
 [43] setosa     setosa     setosa     setosa     setosa     setosa    
 [49] setosa     setosa     versicolor versicolor versicolor versicolor
 [55] versicolor versicolor versicolor versicolor versicolor versicolor
 [61] versicolor versicolor versicolor versicolor versicolor versicolor
 [67] versicolor versicolor versicolor versicolor versicolor versicolor
 [73] versicolor versicolor versicolor versicolor versicolor versicolor
 [79] versicolor versicolor versicolor versicolor versicolor versicolor
 [85] versicolor versicolor versicolor versicolor versicolor versicolor
 [91] versicolor versicolor versicolor versicolor versicolor versicolor
 [97] versicolor versicolor versicolor versicolor virginica  virginica 
[103] virginica  virginica  virginica  virginica  virginica  virginica 
[109] virginica  virginica  virginica  virginica  virginica  virginica 
[115] virginica  virginica  virginica  virginica  virginica  virginica 
[121] virginica  virginica  virginica  virginica  virginica  virginica 
[127] virginica  virginica  virginica  virginica  virginica  virginica 
[133] virginica  virginica  virginica  virginica  virginica  virginica 
[139] virginica  virginica  virginica  virginica  virginica  virginica 
[145] virginica  virginica  virginica  virginica  virginica  virginica 
Levels: virginica setosa versicolor</code></pre>
</div>
</div>
<p>Once we do the re-leveling, we can now run the regression model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>new_cat_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(Sepal.Length <span class="sc">~</span> Species, iris)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>new_cat_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sepal.Length ~ Species, data = iris)

Coefficients:
      (Intercept)      Speciessetosa  Speciesversicolor  
            6.588             -1.582             -0.652  </code></pre>
</div>
</div>
</section>
</section>
<section id="tuesday-february-9th" class="level2">
<h2 class="anchored" data-anchor-id="tuesday-february-9th">Tuesday, February 9th</h2>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
TIL
</div>
</div>
<div class="callout-body-container callout-body">
<p>Include a <em>very brief</em> summary of what you learnt in this class here.</p>
<p>Today, I learnt the following concepts in class:</p>
<ol type="1">
<li>How to make a plot for a model that incorporates more than 1 quantitative covariate</li>
<li>The impact of noise and <span class="math inline">\(\beta\)</span> values on <span class="math inline">\(R^2\)</span></li>
<li>Multiple regression with categorical covariates</li>
</ol>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Credit)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> Credit <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>()</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df) <span class="ot">&lt;-</span> <span class="fu">tolower</span>(<span class="fu">colnames</span>(df))</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 400 × 11
   income limit rating cards   age educat…¹ own   student married region balance
    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt;   &lt;fct&gt;   &lt;fct&gt;    &lt;dbl&gt;
 1   14.9  3606    283     2    34       11 No    No      Yes     South      333
 2  106.   6645    483     3    82       15 Yes   Yes     Yes     West       903
 3  105.   7075    514     4    71       11 No    No      No      West       580
 4  149.   9504    681     3    36       11 Yes   No      No      West       964
 5   55.9  4897    357     2    68       16 No    No      Yes     South      331
 6   80.2  8047    569     4    77       10 No    No      No      South     1151
 7   21.0  3388    259     2    37       12 Yes   No      No      East       203
 8   71.4  7114    512     2    87        9 No    No      No      West       872
 9   15.1  3300    266     5    66       13 Yes   No      No      South      279
10   71.1  6819    491     3    41       19 Yes   Yes     Yes     East      1350
# … with 390 more rows, and abbreviated variable name ¹​education</code></pre>
</div>
</div>
<section id="plotting-a-model-with-more-than-1-quantitative-covariate" class="level4">
<h4 class="anchored" data-anchor-id="plotting-a-model-with-more-than-1-quantitative-covariate">Plotting a model with more than 1 quantitative covariate</h4>
<p>We will look at the following 3 columns: ‘income, rating, limit’.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">'income'</span>, <span class="st">'rating'</span>, <span class="st">'limit'</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>df3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 400 × 3
   income rating limit
    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1   14.9    283  3606
 2  106.     483  6645
 3  105.     514  7075
 4  149.     681  9504
 5   55.9    357  4897
 6   80.2    569  8047
 7   21.0    259  3388
 8   71.4    512  7114
 9   15.1    266  3300
10   71.1    491  6819
# … with 390 more rows</code></pre>
</div>
</div>
<p>If we want to see how the credit limit is related to income and credit rating, we can visualize the following plot</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'plotly'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    last_plot</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    filter</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:graphics':

    layout</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fig <span class="ot">&lt;-</span> <span class="fu">plot_ly</span>(df3, <span class="at">x=</span><span class="sc">~</span>income, <span class="at">y=</span><span class="sc">~</span>rating, <span class="at">z=</span><span class="sc">~</span>limit)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>fig <span class="sc">%&gt;%</span> <span class="fu">add_markers</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-c9898529bdd87cf3e262" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-c9898529bdd87cf3e262">{"x":{"visdat":{"17d05a732107":["function () ","plotlyVisDat"]},"cur_data":"17d05a732107","attrs":{"17d05a732107":{"x":{},"y":{},"z":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d","mode":"markers","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"income"},"yaxis":{"title":"rating"},"zaxis":{"title":"limit"}},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[14.891,106.025,104.593,148.924,55.882,80.18,20.996,71.408,15.125,71.061,63.095,15.045,80.616,43.682,19.144,20.089,53.598,36.496,49.57,42.079,17.7,37.348,20.103,64.027,10.742,14.09,42.471,32.793,186.634,26.813,34.142,28.941,134.181,31.367,20.15,23.35,62.413,30.007,11.795,13.647,34.95,113.659,44.158,36.929,31.861,77.38,19.531,44.646,44.522,43.479,36.362,39.705,44.205,16.304,15.333,32.916,57.1,76.273,10.354,51.872,35.51,21.238,30.682,14.132,32.164,12,113.829,11.187,27.847,49.502,24.889,58.781,22.939,23.989,16.103,33.017,30.622,20.936,110.968,15.354,27.369,53.48,23.672,19.225,43.54,152.298,55.367,11.741,15.56,59.53,20.191,48.498,30.733,16.479,38.009,14.084,14.312,26.067,36.295,83.851,21.153,17.976,68.713,146.183,15.846,12.031,16.819,39.11,107.986,13.561,34.537,28.575,46.007,69.251,16.482,40.442,35.177,91.362,27.039,23.012,27.241,148.08,62.602,11.808,29.564,27.578,26.427,57.202,123.299,18.145,23.793,10.726,23.283,21.455,34.664,44.473,54.663,36.355,21.374,107.841,39.831,91.876,103.893,19.636,17.392,19.529,17.055,23.857,15.184,13.444,63.931,35.864,41.419,92.112,55.056,19.537,31.811,56.256,42.357,53.319,12.238,31.353,63.809,13.676,76.782,25.383,35.691,29.403,27.47,27.33,34.772,36.934,76.348,14.887,121.834,30.132,24.05,22.379,28.316,58.026,10.635,46.102,58.929,80.861,158.889,30.42,36.472,23.365,83.869,58.351,55.187,124.29,28.508,130.209,30.406,23.883,93.039,50.699,27.349,10.403,23.949,73.914,21.038,68.206,57.337,10.793,23.45,10.842,51.345,151.947,24.543,29.567,39.145,39.422,34.909,41.025,15.476,12.456,10.627,38.954,44.847,98.515,33.437,27.512,121.709,15.079,59.879,66.989,69.165,69.943,33.214,25.124,15.741,11.603,69.656,10.503,42.529,60.579,26.532,27.952,29.705,15.602,20.918,58.165,22.561,34.509,19.588,36.364,15.717,22.574,10.363,28.474,72.945,85.425,36.508,58.063,25.936,15.629,41.4,33.657,67.937,180.379,10.588,29.725,27.999,40.885,88.83,29.638,25.988,39.055,15.866,44.978,30.413,16.751,30.55,163.329,23.106,41.532,128.04,54.319,53.401,36.142,63.534,49.927,14.711,18.967,18.036,60.449,16.711,10.852,26.37,24.088,51.532,140.672,42.915,27.272,65.896,55.054,20.791,24.919,21.786,31.335,59.855,44.061,82.706,24.46,45.12,75.406,14.956,75.257,33.694,23.375,27.825,92.386,115.52,14.479,52.179,68.462,18.951,27.59,16.279,25.078,27.229,182.728,31.029,17.765,125.48,49.166,41.192,94.193,20.405,12.581,62.328,21.011,24.23,24.314,32.856,12.414,41.365,149.316,27.794,13.234,14.595,10.735,48.218,30.012,21.551,160.231,13.433,48.577,30.002,61.62,104.483,41.868,12.068,180.682,34.48,39.609,30.111,12.335,53.566,53.217,26.162,64.173,128.669,113.772,61.069,23.793,89,71.682,35.61,39.116,19.782,55.412,29.4,20.974,87.625,28.144,19.349,53.308,115.123,101.788,24.824,14.292,20.088,26.4,19.253,16.529,37.878,83.948,135.118,73.327,25.974,17.316,49.794,12.096,13.364,57.872,37.728,18.701],"y":[283,483,514,681,357,569,259,512,266,491,589,138,394,511,269,200,286,339,448,479,235,458,213,398,156,326,289,333,949,411,413,210,563,162,199,220,455,462,300,264,253,538,351,445,469,564,376,320,205,354,376,301,394,413,138,154,372,367,281,390,364,254,160,251,223,320,694,380,418,505,318,538,355,338,418,224,251,253,468,171,288,317,344,122,232,828,448,182,352,543,431,456,249,388,245,120,367,266,241,607,256,190,531,682,365,259,115,263,449,279,250,231,491,474,268,369,186,626,173,137,128,599,481,117,192,195,433,259,610,279,281,162,407,427,452,257,314,278,175,728,459,483,549,387,228,341,371,150,192,121,435,353,184,344,235,143,338,406,406,235,381,160,515,203,429,367,214,178,219,459,167,299,344,339,750,206,221,292,316,560,294,382,459,335,805,316,309,167,554,326,385,701,287,730,181,398,517,304,169,310,383,529,145,499,392,321,180,358,320,642,243,397,323,383,410,337,215,392,149,370,437,633,451,344,584,411,527,430,341,547,387,378,360,187,579,232,369,388,236,263,262,103,128,460,147,189,265,188,93,134,191,267,621,402,469,304,135,186,215,450,383,665,296,270,380,379,360,433,142,410,217,347,299,353,439,636,257,353,518,248,377,183,581,485,167,156,142,272,387,296,268,287,380,817,205,149,370,321,204,372,355,289,365,352,536,165,287,298,332,494,369,396,386,534,656,296,522,340,129,229,126,236,282,982,223,364,721,508,297,527,329,291,377,261,351,270,438,119,377,707,301,299,260,280,401,137,420,754,112,389,155,374,507,342,292,832,442,188,339,344,434,362,382,433,685,489,564,263,440,599,466,173,293,383,368,413,515,142,366,214,538,574,409,282,180,398,287,126,482,503,747,472,196,138,410,307,296,321,192,415],"z":[3606,6645,7075,9504,4897,8047,3388,7114,3300,6819,8117,1311,5308,6922,3291,2525,3714,4378,6384,6626,2860,6378,2631,5179,1757,4323,3625,4534,13414,5611,5666,2733,7838,1829,2646,2558,6457,6481,3899,3461,3327,7659,4763,6257,6375,7569,5043,4431,2252,4569,5183,3969,5441,5466,1499,1786,4742,4779,3480,5294,5198,3089,1671,2998,2937,4160,9704,5099,5619,6819,3954,7402,4923,4523,5390,3180,3293,3254,6662,2101,3449,4263,4433,1433,2906,12066,6340,2271,4307,7518,5767,6040,2832,5435,3075,855,5382,3388,2963,8494,3736,2433,7582,9540,4768,3182,1337,3189,6033,3261,3271,2959,6637,6386,3326,4828,2117,9113,2161,1410,1402,8157,7056,1300,2529,2531,5533,3411,8376,3461,3821,1568,5443,5829,5835,3500,4116,3613,2073,10384,6045,6754,7416,4896,2748,4673,5110,1501,2420,886,5728,4831,2120,4612,3155,1362,4284,5521,5550,3000,4865,1705,7530,2330,5977,4527,2880,2327,2820,6179,2021,4270,4697,4745,10673,2168,2607,3965,4391,7499,3584,5180,6420,4090,11589,4442,3806,2179,7667,4411,5352,9560,3933,10088,2120,5384,7398,3977,2000,4159,5343,7333,1448,6784,5310,3878,2450,4391,4327,9156,3206,5309,4351,5245,5289,4229,2762,5395,1647,5222,5765,8760,6207,4613,7818,5673,6906,5614,4668,7555,5137,4776,4788,2278,8244,2923,4986,5149,2910,3557,3351,906,1233,6617,1787,2001,3211,2220,905,1551,2430,3202,8603,5182,6386,4221,1774,2493,2561,6196,5184,9310,4049,3536,5107,5013,4952,5833,1349,5565,3085,4866,3690,4706,5869,8732,3476,5000,6982,3063,5319,1852,8100,6396,2047,1626,1552,3098,5274,3907,3235,3665,5096,11200,2532,1389,5140,4381,2672,5051,4632,3526,4964,4970,7506,1924,3762,3874,4640,7010,4891,5429,5227,7685,9272,3907,7306,4712,1485,2586,1160,3096,3484,13913,2863,5072,10230,6662,3673,7576,4543,3976,5228,3402,4756,3409,5884,855,5303,10278,3807,3922,2955,3746,5199,1511,5380,10748,1134,5145,1561,5140,7140,4716,3873,11966,6090,2539,4336,4471,5891,4943,5101,6127,9824,6442,7871,3615,5759,8028,6135,2150,3782,5354,4840,5673,7167,1567,4941,2860,7760,8029,5495,3274,1870,5640,3683,1357,6827,7100,10578,6555,2308,1335,5758,4100,3838,4171,2525,5524],"type":"scatter3d","mode":"markers","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>This models a linear relationship, which in 3-dimensions is a plane (a hyperplane)</p>
<ul>
<li>Was shown in class what the hyperplane looked like but weren’t given the code, so couldn’t include that in the summary</li>
</ul>
<p>The regression model is as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(limit <span class="sc">~</span> income <span class="sc">+</span> rating, df3)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = limit ~ income + rating, data = df3)

Coefficients:
(Intercept)       income       rating  
  -532.4711       0.5573      14.7711  </code></pre>
</div>
</div>
<ul>
<li>Have 3 different coefficients</li>
<li>2nd/3rd numbers are the slopes associated with the income and rating</li>
</ul>
<p>What is the interpretation for the coefficients?</p>
<ol type="1">
<li><span class="math inline">\(\beta_0\)</span> is the expected value of <span class="math inline">\(y\)</span> when <span class="math inline">\(income = 0\)</span> and <span class="math inline">\(rating = 0\)</span> (the credit limit with 0 income and 0 rating is -532) –&gt; this is an extrapolation</li>
<li><span class="math inline">\(\beta_1\)</span> is saying that if <span class="math inline">\(rating\)</span> is held constant and <span class="math inline">\(income\)</span> changes by 1 unit, then the corresponding change in the ‘limit’ is <span class="math inline">\(0.5573\)</span>.</li>
<li><span class="math inline">\(\beta_2\)</span> is saying that if <span class="math inline">\(income\)</span> is held constant and <span class="math inline">\(rating\)</span> changes by 1 unit, then the corresponding change in the ‘limit’ is <span class="math inline">\(14.7711\)</span>.</li>
</ol>
<p>What about the significance?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = limit ~ income + rating, data = df3)

Residuals:
    Min      1Q  Median      3Q     Max 
-420.97 -121.77   14.97  126.72  485.48 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -532.47115   24.17283 -22.028   &lt;2e-16 ***
income         0.55727    0.42349   1.316    0.189    
rating        14.77115    0.09647 153.124   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 182.3 on 397 degrees of freedom
Multiple R-squared:  0.9938,    Adjusted R-squared:  0.9938 
F-statistic: 3.18e+04 on 2 and 397 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The <span class="math inline">\(p\)</span>-value for ‘rating’ is very significant, while its not significant for ‘income’</p>
<ul>
<li><p>Multi-colinearity issue with the 3D model</p>
<ol type="1">
<li>Not idealisitic that if we hold rating constant and income increases, by one unit then limit increase by 0.5573. –&gt; You can’t change income by 1 without impacting rating</li>
</ol></li>
</ul>
</section>
<section id="the-impact-of-noise-and-beta-values-on-r2" class="level4">
<h4 class="anchored" data-anchor-id="the-impact-of-noise-and-beta-values-on-r2">The impact of noise and <span class="math inline">\(\beta\)</span> values on <span class="math inline">\(R^2\)</span></h4>
<p>This first code chunk shows the model with very little noise and the output model summary to demonstrate the very high <span class="math inline">\(R^2\)</span> and <span class="math inline">\(p\)</span>-value that occurs with very low noise</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">100</span>,<span class="dv">1</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fl">1.0</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="fl">3.0</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>) <span class="sc">*</span> <span class="fl">0.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in b0 + b1 * x + rnorm(100) * 0.1: longer object length is not a
multiple of shorter object length</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y, <span class="at">pch =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.250396 -0.062611 -0.000858  0.076603  0.170069 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.9929262  0.0194708      51   &lt;2e-16 ***
x           3.0000750  0.0003364    8918   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.09857 on 99 degrees of freedom
Multiple R-squared:      1, Adjusted R-squared:      1 
F-statistic: 7.953e+07 on 1 and 99 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>This next code chunk shows what happens with a much greater noise value. The intercept <span class="math inline">\(p\)</span>-value is much high than the previous model and the <span class="math inline">\(R^2\)</span> value decreases as well.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">100</span>,<span class="dv">1</span>)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="fl">1.0</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="fl">3.0</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>) <span class="sc">*</span> <span class="dv">20</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in b0 + b1 * x + rnorm(100) * 20: longer object length is not a
multiple of shorter object length</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y, <span class="at">pch =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x)

Residuals:
    Min      1Q  Median      3Q     Max 
-50.748 -14.100   0.781  16.183  54.825 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  7.25908    4.19133   1.732   0.0864 .  
x            2.94188    0.07242  40.625   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 21.22 on 99 degrees of freedom
Multiple R-squared:  0.9434,    Adjusted R-squared:  0.9428 
F-statistic:  1650 on 1 and 99 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>To summarize:</p>
<ul>
<li><p>Lower noise increases the <span class="math inline">\(R^2\)</span> value</p></li>
<li><p>If you make <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and noise values super small, then p-value will be super high and lead to a low <span class="math inline">\(R^2\)</span> value</p></li>
<li><p>Can have high <span class="math inline">\(p\)</span>-value with low <span class="math inline">\(R^2\)</span> value, but CANT have low <span class="math inline">\(p\)</span>-value with high <span class="math inline">\(R^2\)</span> value</p></li>
</ul>
</section>
<section id="multiple-regression-with-categorical-covariates" class="level4">
<h4 class="anchored" data-anchor-id="multiple-regression-with-categorical-covariates">Multiple regression with categorical covariates</h4>
<p>To demonstrate how to incorporate both categorical and quantitative covariates into a regression model, we will use the rating and marital status from the Credit dataset to try and predict the limit.</p>
<p>To create the models, you need to run 2 separate models using income, rating, and marital status to predict limit. 1. once for when student is yes 1. once for when student is no</p>
<ul>
<li>By adding the categorical variable, you are adding an additional intercept term</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(limit <span class="sc">~</span> rating <span class="sc">+</span> married, df)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = limit ~ rating + married, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-404.83 -126.56   20.86  131.80  456.19 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -528.088     25.204 -20.952   &lt;2e-16 ***
rating        14.875      0.059 252.123   &lt;2e-16 ***
marriedYes   -25.972     18.714  -1.388    0.166    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 182.2 on 397 degrees of freedom
Multiple R-squared:  0.9938,    Adjusted R-squared:  0.9938 
F-statistic: 3.181e+04 on 2 and 397 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df) <span class="sc">+</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x=</span>rating, <span class="at">y=</span>limit, <span class="at">color=</span>married)) <span class="sc">+</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="fu">aes</span>(<span class="at">x=</span>rating, <span class="at">y=</span>limit, <span class="at">fill=</span>married))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The model above does have 2 different lines, they are just so close together, that you can’t really see it, which implies that they have the same regression line. From the model summary, you can see that the <span class="math inline">\(p\)</span>-value for marital status is very high, which indicates that it is not a good predictor of someones credit limit.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>